development:
  host: psql
  pool: 5
  adapter:  postgresql
  encoding: unicode

  database: eastflower
  username: rails
  password: qwerty

production:
  host: psql
  pool: 5
  adapter:  postgresql
  encoding: unicode

  database: eastflower
  username: rails
  password: qwerty
